namespace SpriteKind {
    export const Rainbow = SpriteKind.create()
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    game.showLongText("Move with arrow keys. You deal damage if you hit the small cat while you are moving. You get hurt if you get hit while you are not moving.", DialogLayout.Center)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Projectile, function (sprite, otherSprite) {
    if (canCollide) {
        if (sprite.vx != 0 || sprite.vy != 0) {
            info.player2.changeLifeBy(-1)
            music.playSoundEffect(music.createSoundEffect(WaveShape.Sine, 5000, 0, 255, 0, 500, SoundExpressionEffect.None, InterpolationCurve.Linear), SoundExpressionPlayMode.InBackground)
        } else {
            info.player1.changeLifeBy(-1)
            music.knock.play()
        }
        canCollide = false
    }
})
info.player1.onLifeZero(function () {
    game.over(false)
})
info.player2.onLifeZero(function () {
    game.over(true)
})
let canCollide = false
scene.setBackgroundColor(10)
game.setDialogFrame(assets.image`Rainbow frame`)
game.showLongText("Rainbow cat", DialogLayout.Top)
game.showLongText("by Rubén and papá", DialogLayout.Top)
game.showLongText("Press A for instructions.", DialogLayout.Top)
canCollide = true
let rainbow = sprites.create(img`
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    `, SpriteKind.Rainbow)
let rainbow2 = sprites.create(img`
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    `, SpriteKind.Rainbow)
let rainbow3 = sprites.create(img`
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    `, SpriteKind.Rainbow)
let rainbow4 = sprites.create(img`
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    `, SpriteKind.Rainbow)
let cat = sprites.create(img`
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    `, SpriteKind.Player)
animation.runImageAnimation(
cat,
assets.animation`myAnim`,
100,
true
)
animation.runImageAnimation(
rainbow,
assets.animation`myAnim0`,
200,
true
)
animation.runImageAnimation(
rainbow2,
assets.animation`myAnim0`,
200,
true
)
animation.runImageAnimation(
rainbow3,
assets.animation`myAnim0`,
200,
true
)
animation.runImageAnimation(
rainbow4,
assets.animation`myAnim0`,
200,
true
)
controller.moveSprite(cat)
cat.setStayInScreen(true)
let projectile = sprites.createProjectileFromSide(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, randint(-100, -50), -50)
animation.runImageAnimation(
projectile,
[img`
    e e e . . . . e e e . . . . 
    c d d c . . c d d c . . . . 
    c b d d f f d d b c . . . . 
    c 3 b d d b d b 3 c . . . . 
    f b 3 d d d d 3 b f . . . . 
    e d d d d d d d d e . . . . 
    e d f d d d d f d e . b f b 
    f d d f d d f d d f . f d f 
    f b d d b b d d 2 f . f d f 
    . f 2 2 2 2 2 2 b b f f d f 
    . f b d d d d d d b b d b f 
    . f d d d d d b d d f f f . 
    . f d f f f d f f d f . . . 
    . f f . . f f . . f f . . . 
    `,img`
    . . . . . . . . . . . . . . 
    e e e . . . . e e e . . . . 
    c d d c . . c d d c . . . . 
    c b d d f f d d b c . . . . 
    c 3 b d d b d b 3 c . . . . 
    f b 3 d d d d 3 b f . . . . 
    e d d d d d d d d e . . . . 
    e d f d d d d f d e b f b . 
    f d d f d d f d d f f d f . 
    f b d d b b d d 2 b f d f . 
    . f 2 2 2 2 2 2 d b d b f . 
    . f d d d d d d d f f f . . 
    . f d b d f f f d f . . . . 
    . . f f f f . . f f . . . . 
    `,img`
    . . . . . . . . . . . . . . 
    e e e . . . . e e e . . . . 
    c d d c . . c d d c . . . . 
    c b d d f f d d b c . . . . 
    c 3 b d d b d b 3 c . . . . 
    f b 3 d d d d 3 b f . . . . 
    e d d d d d d d d e . . . . 
    e d f d d d d f d e . b f b 
    f d d f d d f d d f . f d f 
    f b d d b b d d 2 b f f d f 
    . f 2 2 2 2 2 2 d b b d b f 
    . f d d d d d d d f f f f . 
    . . f d b d f d f . . . . . 
    . . . f f f f f f . . . . . 
    `],
100,
true
)
projectile.setBounceOnWall(true)
info.player1.setLife(4000)
info.player2.setLife(100)
game.onUpdate(function () {
    rainbow.setPosition(cat.x - 28, cat.y)
    rainbow2.setPosition(rainbow.x - 36, rainbow.y)
    rainbow3.setPosition(rainbow2.x - 36, rainbow2.y)
    rainbow4.setPosition(rainbow3.x - 36, rainbow3.y)
    if (!(cat.overlapsWith(projectile))) {
        canCollide = true
    }
})
